"use client";

import { FormEvent, useCallback, useEffect, useState } from "react";

type CaseRow = { id: string; subject: string; description: string; status: string; resolution: string | null; orderId: string | null; createdAt: string };

export function SupportCenter() {
  const [cases, setCases] = useState<CaseRow[]>([]);
  const [subject, setSubject] = useState(""); const [description, setDescription] = useState(""); const [orderId, setOrderId] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [notice, setNotice] = useState("");
  const load = useCallback(async () => { const response = await fetch("/api/support"); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to load your support requests."); setCases(data.cases); }, []);
  useEffect(() => { const timer = window.setTimeout(() => { void load().catch((e) => setError(e.message)); }, 0); return () => window.clearTimeout(timer); }, [load]);
  async function submit(event: FormEvent) { event.preventDefault(); setBusy(true); setError(""); setNotice(""); try { const response = await fetch("/api/support", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ subject, description, orderId: orderId.trim() || undefined }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to contact PackAM."); setSubject(""); setDescription(""); setOrderId(""); setNotice("Got it. PackAM operations will take a look."); await load(); } catch (e) { setError(e instanceof Error ? e.message : "Unable to contact PackAM."); } finally { setBusy(false); } }
  return <main className="min-h-screen bg-[#f7f5ee]"><div className="packam-container py-8"><p className="text-xs font-bold uppercase tracking-wider text-black/40">We’re here to help</p><h1 className="mt-1 text-3xl font-black">Support</h1><p className="mt-2 text-sm text-black/55">Tell us what happened and we’ll look into it.</p><form onSubmit={submit} className="mt-5 space-y-3 rounded-2xl bg-white p-5"><input value={subject} onChange={(e) => setSubject(e.target.value)} required minLength={4} maxLength={120} placeholder="What do you need help with?" className="w-full rounded-xl border border-black/10 px-4 py-3 text-sm"/><input value={orderId} onChange={(e) => setOrderId(e.target.value)} maxLength={64} placeholder="Order reference (optional)" className="w-full rounded-xl border border-black/10 px-4 py-3 text-sm"/><textarea value={description} onChange={(e) => setDescription(e.target.value)} required minLength={10} maxLength={3000} rows={4} placeholder="A few details will help us sort it out." className="w-full rounded-xl border border-black/10 px-4 py-3 text-sm"/><button disabled={busy} className="rounded-full bg-black px-6 py-3 text-sm font-black text-white disabled:opacity-50">{busy ? "Sending…" : "Send to PackAM"}</button>{error && <p role="alert" className="text-sm text-red-700">{error}</p>}{notice && <p role="status" className="text-sm text-green-800">{notice}</p>}</form><h2 className="mt-8 text-xl font-black">Your requests</h2><div className="mt-3 space-y-3">{cases.map((item) => <article key={item.id} className="rounded-2xl bg-white p-4"><div className="flex justify-between gap-3"><h3 className="font-black">{item.subject}</h3><span className="text-xs font-bold text-black/45">{item.status.replaceAll("_", " ")}</span></div><p className="mt-2 text-sm text-black/65">{item.description}</p>{item.resolution && <p className="mt-3 rounded-xl bg-[#fff8df] p-3 text-sm">{item.resolution}</p>}<p className="mt-2 text-xs text-black/40">{new Date(item.createdAt).toLocaleString()}{item.orderId ? ` · Order ${item.orderId}` : ""}</p></article>)}{!cases.length && <p className="rounded-2xl bg-white p-5 text-sm text-black/50">No support requests yet.</p>}</div></div></main>;
}
