"use client";

import { FormEvent, useEffect, useState } from "react";

type ProductRequest = { id: string; requestedName: string; quantity: number; variant: string | null; description: string | null; status: string; createdAt: string; product: { id: string; name: string } | null };
const statusCopy: Record<string, string> = { PENDING: "Request received.", CHECKING: "We’re checking around for it 👀", AVAILABLE: "Found it!", UNAVAILABLE: "We couldn’t find that one this time.", CANCELLED: "Request cancelled." };

export function ProductRequestList({ initialProductName = "" }: { initialProductName?: string }) {
  const [requests, setRequests] = useState<ProductRequest[]>([]);
  const [productName, setProductName] = useState(initialProductName); const [quantity, setQuantity] = useState(1); const [variant, setVariant] = useState(""); const [note, setNote] = useState("");
  const [busy, setBusy] = useState(false); const [error, setError] = useState(""); const [success, setSuccess] = useState("");
  useEffect(() => { const timer = window.setTimeout(() => { void fetch("/api/product-requests").then(async (r) => { const data = await r.json(); if (!r.ok) throw new Error(data.error); setRequests(data.requests); }).catch((e) => setError(e.message || "Unable to load requests.")); }, 0); return () => window.clearTimeout(timer); }, []);
  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setBusy(true); setError(""); setSuccess("");
    try {
      const response = await fetch("/api/product-requests", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ productName, quantity, variant, note }) });
      const data = await response.json(); if (!response.ok) throw new Error(data.error || "We couldn’t send that request.");
      setRequests((current) => [{ ...data.request, quantity, variant: variant || null, description: note || null, product: null }, ...current]);
      setProductName(""); setQuantity(1); setVariant(""); setNote(""); setSuccess("Got it. We’ll check around 👀");
    } catch (e) { setError(e instanceof Error ? e.message : "We couldn’t send that request."); } finally { setBusy(false); }
  }
  return <div className="mt-7 grid gap-6 lg:grid-cols-[minmax(0,1fr)_minmax(0,1fr)]"><form onSubmit={submit} className="h-fit rounded-3xl border border-black/5 bg-white p-5 sm:p-7"><h2 className="text-xl font-black">Can’t find what you need?</h2><p className="mt-1 text-sm text-black/55">Tell us what you’re looking for. We’ll check around.</p><label className="mt-5 block text-sm font-bold">Product name<input required maxLength={120} value={productName} onChange={(e) => setProductName(e.target.value)} placeholder="Scientific Calculator" className="mt-1 w-full rounded-xl border border-black/10 px-3 py-3 font-normal" /></label><div className="mt-3 grid grid-cols-2 gap-3"><label className="text-sm font-bold">Quantity<input required type="number" min={1} max={99} value={quantity} onChange={(e) => setQuantity(Number(e.target.value))} className="mt-1 w-full rounded-xl border border-black/10 px-3 py-3 font-normal" /></label><label className="text-sm font-bold">Variant (optional)<input maxLength={120} value={variant} onChange={(e) => setVariant(e.target.value)} placeholder="Casio FX-991ES Plus" className="mt-1 w-full rounded-xl border border-black/10 px-3 py-3 font-normal" /></label></div><label className="mt-3 block text-sm font-bold">Additional note (optional)<textarea maxLength={500} rows={3} value={note} onChange={(e) => setNote(e.target.value)} placeholder="Any shop around campus is fine." className="mt-1 w-full rounded-xl border border-black/10 px-3 py-3 font-normal" /></label>{error && <p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}{success && <p role="status" className="mt-3 text-sm font-bold text-green-800">{success}</p>}<button disabled={busy} className="mt-4 rounded-full bg-black px-6 py-3 text-sm font-black text-white disabled:opacity-50">{busy ? "Sending…" : "Send request"}</button></form><section><h2 className="text-xl font-black">Your requests</h2>{requests.length ? <div className="mt-3 space-y-3">{requests.map((item) => <article key={item.id} className="rounded-2xl border border-black/5 bg-white p-4"><div className="flex justify-between gap-3"><strong>{item.requestedName} × {item.quantity}</strong><span className="text-xs font-bold text-black/55">{statusCopy[item.status] ?? item.status}</span></div>{item.variant && <p className="mt-1 text-sm text-black/60">{item.variant}</p>}{item.description && <p className="mt-1 text-sm text-black/55">{item.description}</p>}{item.status === "AVAILABLE" && item.product && <a href={`/products/${item.product.id}`} className="mt-2 inline-block text-sm font-bold underline">View {item.product.name} →</a>}<p className="mt-2 text-xs text-black/35">{new Date(item.createdAt).toLocaleDateString()}</p></article>)}</div> : <p className="mt-3 rounded-2xl bg-white p-5 text-sm text-black/55">No product requests yet.</p>}</section></div>;
}
