"use client";

import { useState } from "react";

type SupportCase = { id: string; subject: string; description: string; status: string; resolution: string | null; orderId: string | null; createdAt: Date; user: { firstName: string | null; lastName: string | null; email: string } };

export function AdminSupport({ cases }: { cases: SupportCase[] }) {
  const [rows, setRows] = useState(cases); const [busyId, setBusyId] = useState(""); const [error, setError] = useState("");
  async function update(id: string, status: string) { setBusyId(id); setError(""); try { const row = rows.find((item) => item.id === id)!; const resolution = status === "RESOLVED" ? (window.prompt("Resolution note", row.resolution ?? "") ?? "") : row.resolution ?? undefined; const response = await fetch(`/api/admin/support/${id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ status, resolution }) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || "Unable to update the case."); setRows((current) => current.map((item) => item.id === id ? { ...item, status: data.case.status, resolution: data.case.resolution } : item)); } catch (e) { setError(e instanceof Error ? e.message : "Unable to update the case."); } finally { setBusyId(""); } }
  return <><div className="mt-4 space-y-3">{rows.map((item) => <article key={item.id} className="rounded-2xl bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-black">{item.subject}</h2><p className="mt-1 text-xs text-black/50">{item.user.firstName} {item.user.lastName} · {item.user.email} · {new Date(item.createdAt).toLocaleString()}</p></div><strong className="text-xs">{item.status}</strong></div><p className="mt-3 text-sm">{item.description}</p>{item.orderId && <p className="mt-2 text-xs text-black/45">Order {item.orderId}</p>}{item.resolution && <p className="mt-2 rounded-xl bg-[#f7f5ee] p-3 text-sm">Resolution: {item.resolution}</p>}<div className="mt-4 flex flex-wrap gap-2">{item.status === "OPEN" && <button disabled={busyId === item.id} onClick={() => void update(item.id, "IN_PROGRESS")} className="rounded-full border px-4 py-2 text-xs font-bold">Start investigating</button>}{item.status === "IN_PROGRESS" && <><button disabled={busyId === item.id} onClick={() => void update(item.id, "ESCALATED")} className="rounded-full border px-4 py-2 text-xs font-bold">Escalate</button><button disabled={busyId === item.id} onClick={() => void update(item.id, "RESOLVED")} className="rounded-full bg-black px-4 py-2 text-xs font-bold text-white">Resolve with note</button></>}{item.status === "ESCALATED" && <><button disabled={busyId === item.id} onClick={() => void update(item.id, "IN_PROGRESS")} className="rounded-full border px-4 py-2 text-xs font-bold">Resume investigation</button><button disabled={busyId === item.id} onClick={() => void update(item.id, "RESOLVED")} className="rounded-full bg-black px-4 py-2 text-xs font-bold text-white">Resolve with note</button></>}{item.status === "RESOLVED" && <button disabled={busyId === item.id} onClick={() => void update(item.id, "CLOSED")} className="rounded-full border px-4 py-2 text-xs font-bold">Close case</button>}</div></article>)}{!rows.length && <p className="rounded-2xl bg-white p-5 text-sm text-black/50">No open support cases.</p>}</div>{error && <p role="alert" className="mt-4 text-sm text-red-700">{error}</p>}</>;
}
