"use client";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useState } from "react";

type Item={id:string;requestedName:string;quantity:number;variant:string|null;description:string|null;status:string;createdAt:Date;user:{firstName:string|null;lastName:string|null;email:string};product:{id:string;name:string}|null};
type Product={id:string;name:string};
export function AdminRequests({requests,products}:{requests:Item[];products:Product[]}){
 const router=useRouter();const [selected,setSelected]=useState<Record<string,string>>({});const [busy,setBusy]=useState("");const [error,setError]=useState("");
 async function update(id:string,status:string){setBusy(id);setError("");try{const response=await fetch(`/api/admin/product-requests/${id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({status,...(status==="AVAILABLE"?{productId:selected[id]}:{})})});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to update request.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to update request.");}finally{setBusy("");}}
 return <><p className="mt-2 text-sm text-black/55">Latest 100 · students are notified when you change a request status.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<div className="mt-5 grid gap-3">{requests.map((item)=><article key={item.id} className="rounded-2xl bg-white p-5"><div className="flex flex-wrap justify-between gap-3"><div><p className="font-black">{item.requestedName} × {item.quantity}</p><p className="mt-1 text-xs text-black/50">{item.user.firstName} {item.user.lastName} · {item.user.email} · {item.createdAt.toLocaleString()}</p></div><strong className="text-sm">{item.status}</strong></div>{item.variant&&<p className="mt-3 text-sm">Variant: {item.variant}</p>}{item.description&&<p className="mt-1 text-sm text-black/60">Note: {item.description}</p>}{item.product&&<p className="mt-2 text-sm">Associated product: <Link className="underline" href={`/products/${item.product.id}`}>{item.product.name}</Link></p>}<div className="mt-4 flex flex-wrap gap-2">{item.status==="PENDING"&&<button disabled={!!busy} onClick={()=>void update(item.id,"CHECKING")} className="rounded-full bg-black px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Start checking</button>}{item.status==="CHECKING"&&<><select aria-label={`Product for request ${item.requestedName}`} value={selected[item.id]??item.product?.id??""} onChange={e=>setSelected({...selected,[item.id]:e.target.value})} className="rounded-xl border border-black/10 bg-white px-3 py-2 text-sm"><option value="">Choose existing product</option>{products.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select><button disabled={!!busy||!selected[item.id]&&!item.product} onClick={()=>void update(item.id,"AVAILABLE")} className="rounded-full bg-black px-4 py-2 text-xs font-bold text-white disabled:opacity-50">Mark found</button><button disabled={!!busy} onClick={()=>void update(item.id,"UNAVAILABLE")} className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold disabled:opacity-50">Couldn’t find</button><Link href="/admin/products/new" className="rounded-full border border-black/15 px-4 py-2 text-xs font-bold">Add a product, then return here</Link></>}</div></article>)}{!requests.length&&<p className="rounded-2xl bg-white p-6 text-sm text-black/55">No product requests.</p>}</div></>;
}
