"use client";
import { FormEvent,useState } from "react";
import { useRouter } from "next/navigation";
type Category={id:string;name:string;slug:string;description:string|null;isActive:boolean;_count:{products:number}};
export function AdminCategories({categories}:{categories:Category[]}){
 const router=useRouter();const [error,setError]=useState("");const [busy,setBusy]=useState(false);
 async function send(url:string,method:string,body:unknown){setBusy(true);setError("");try{const r=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save category.");router.refresh();}catch(e){setError(e instanceof Error?e.message:"Unable to save category.");}finally{setBusy(false);}}
 function create(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);void send("/api/admin/categories","POST",Object.fromEntries(f));e.currentTarget.reset();}
 return <><p className="mt-2 text-sm text-black/55">Disabling a category hides its products from the student catalogue; it does not delete products or order history.</p>{error&&<p role="alert" className="mt-3 text-sm text-red-700">{error}</p>}<form onSubmit={create} className="mt-5 flex flex-wrap items-end gap-3 rounded-2xl bg-white p-5"><label className="min-w-48 flex-1 text-xs font-bold">New category<input required name="name" placeholder="Stationery" className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2 text-sm font-normal"/></label><label className="min-w-48 flex-1 text-xs font-bold">Description<input name="description" placeholder="Books and supplies" className="mt-1 w-full rounded-lg border border-black/10 px-3 py-2 text-sm font-normal"/></label><button disabled={busy} className="rounded-full bg-black px-5 py-2.5 text-sm font-bold text-white disabled:opacity-50">Add category</button></form><div className="mt-4 overflow-x-auto rounded-2xl bg-white"><table className="w-full min-w-[640px] text-left text-sm"><thead className="bg-black/5 text-xs uppercase text-black/50"><tr><th className="px-4 py-3">Category</th><th className="px-4 py-3">Slug</th><th className="px-4 py-3">Products</th><th className="px-4 py-3">Status</th><th className="px-4 py-3">Action</th></tr></thead><tbody className="divide-y divide-black/5">{categories.map(c=><tr key={c.id}><td className="px-4 py-3 font-bold">{c.name}</td><td className="px-4 py-3">{c.slug}</td><td className="px-4 py-3">{c._count.products}</td><td className="px-4 py-3">{c.isActive?"Active":"Hidden"}</td><td className="px-4 py-3"><button disabled={busy} onClick={()=>void send(`/api/admin/categories/${c.id}`,"PATCH",{isActive:!c.isActive})} className="rounded-full border border-black/15 px-3 py-1.5 text-xs font-bold">{c.isActive?"Disable":"Enable"}</button></td></tr>)}</tbody></table></div></>;
}
