import Link from "next/link";
import { OrderStatus } from "@prisma/client";
import { db } from "../../../lib/db";

const labels: Record<string,string> = { PAYMENT_CONFIRMED:"Payment confirmed", FINDING_RUNNER:"Finding runner", RUNNER_ASSIGNED:"Runner assigned", SOURCING_PRODUCT:"Sourcing", OUT_FOR_DELIVERY:"Out for delivery", DELIVERED:"Completed", REFUND_PROCESSING:"Refund processing", REFUNDED:"Refunded", FAILED:"Failed", CANCELLED:"Cancelled", PENDING_PAYMENT:"Pending payment" };
export default async function AdminOrdersPage({ searchParams }: { searchParams: Promise<{ status?: string; page?: string }> }) {
  const params = await searchParams; const filter = Object.values(OrderStatus).includes(params.status as OrderStatus) ? params.status as OrderStatus : undefined; const page = Math.max(1, Number(params.page) || 1); const take = 50;
  const where = filter ? { status: filter } : {};
  const [orders,total] = await Promise.all([db.order.findMany({ where, orderBy: { createdAt: "desc" }, skip: (page - 1) * take, take, select: { id:true,status:true,total:true,currency:true,createdAt:true,user:{select:{firstName:true,lastName:true,email:true}},payment:{select:{status:true}} } }), db.order.count({ where })]);
  return <main className="min-h-screen bg-[#f7f5ee]"><div className="packam-container py-8"><h1 className="text-3xl font-black">Orders</h1><div className="mt-4 flex flex-wrap gap-2"><Link href="/admin/orders" className="rounded-full bg-white px-4 py-2 text-sm font-bold">All</Link>{Object.values(OrderStatus).map((status)=><Link key={status} href={`/admin/orders?status=${status}`} className={`rounded-full px-4 py-2 text-sm font-bold ${filter===status?"bg-[#feb80a]":"bg-white"}`}>{labels[status]??status}</Link>)}</div><section className="mt-5 overflow-hidden rounded-2xl bg-white"><div className="divide-y divide-black/5">{orders.map((order)=><Link key={order.id} href={`/admin/orders/${order.id}`} className="grid gap-2 p-4 hover:bg-black/[0.02] sm:grid-cols-[1.4fr_1fr_1fr_auto]"><div><p className="font-black">{order.user.firstName} {order.user.lastName}</p><p className="text-xs text-black/45">{order.id}</p></div><p className="text-sm">{labels[order.status]??order.status}</p><p className="text-sm">Payment: {order.payment?.status ?? "missing"}</p><p className="text-sm font-black">₦{order.total.toLocaleString()}</p></Link>)}</div>{!orders.length&&<p className="p-8 text-sm text-black/50">No orders in this view.</p>}</section><p className="mt-3 text-xs text-black/45">{total} orders · Page {page}</p>{page>1&&<Link className="mr-4 text-sm font-bold underline" href={`/admin/orders?${filter?`status=${filter}&`:""}page=${page-1}`}>Previous</Link>}{page*take<total&&<Link className="text-sm font-bold underline" href={`/admin/orders?${filter?`status=${filter}&`:""}page=${page+1}`}>Next</Link>}</div></main>;
}
