import { PrintJobStatus } from "@prisma/client";

const allowedTransitions: Record<PrintJobStatus, readonly PrintJobStatus[]> = {
  DRAFT: ["READY_FOR_PAYMENT", "CANCELLED", "FAILED"],
  READY_FOR_PAYMENT: ["PAYMENT_CONFIRMED", "CANCELLED", "FAILED"],
  PAYMENT_CONFIRMED: ["FINDING_RUNNER", "REFUND_PROCESSING"],
  FINDING_RUNNER: ["RUNNER_ASSIGNED", "REFUND_PROCESSING", "CANCELLED"],
  RUNNER_ASSIGNED: ["DOCUMENT_RECEIVED", "DOCUMENT_UNREADABLE", "PRINT_FAILED", "REFUND_PROCESSING"],
  DOCUMENT_RECEIVED: ["PRINTING", "DOCUMENT_UNREADABLE", "PRINT_FAILED", "REFUND_PROCESSING"],
  PRINTING: ["PRINTED", "DOCUMENT_UNREADABLE", "PRINT_FAILED", "REFUND_PROCESSING"],
  PRINTED: ["OUT_FOR_DELIVERY", "REFUND_PROCESSING"],
  OUT_FOR_DELIVERY: ["DELIVERED", "REFUND_PROCESSING"],
  DELIVERED: [],
  CANCELLED: ["REFUND_PROCESSING"],
  DOCUMENT_UNREADABLE: ["RUNNER_ASSIGNED", "REFUND_PROCESSING"],
  PRINT_FAILED: ["RUNNER_ASSIGNED", "REFUND_PROCESSING"],
  REFUND_PROCESSING: ["REFUNDED", "FAILED"],
  REFUNDED: [],
  FAILED: ["REFUND_PROCESSING"],
};

export function canTransitionPrintJob(from: PrintJobStatus, to: PrintJobStatus) {
  return allowedTransitions[from].includes(to);
}
