import Link from "next/link";
import { db } from "../../../lib/db";
import { getRunnerAcceptanceTimeoutMinutes } from "../../../lib/orders/price-policy";

export default async function AdminExceptionsPage(){
 const now = new Date();
 const [incidents,priceChanges,payments,refunds,oldOrders,staleRequests]=await Promise.all([db.incident.findMany({where:{status:{in:["OPEN","INVESTIGATING"]}},orderBy:{createdAt:"asc"},take:50,select:{id:true,type:true,status:true,description:true,createdAt:true,order:{select:{id:true}}}}),db.orderItemSourcing.findMany({where:{status:"PRICE_PENDING"},orderBy:{createdAt:"asc"},take:50,select:{id:true,actualUnitPrice:true,catalogueUnitPrice:true,orderItem:{select:{productName:true,order:{select:{id:true}}}},orderSource:{select:{vendor:{select:{name:true}}}}}}),db.payment.findMany({where:{OR:[{status:"RECONCILIATION_REQUIRED"},{status:"SUCCESS",orderId:null}]},take:50,select:{id:true,transactionReference:true,status:true,amount:true,user:{select:{email:true}}}}),db.refund.findMany({where:{status:"FAILED"},take:50,select:{id:true,amount:true,reason:true,order:{select:{id:true}}}}),db.order.findMany({where:{status:"FINDING_RUNNER",assignedRunnerId:null,findingRunnerAt:{lte:new Date(now.getTime()-getRunnerAcceptanceTimeoutMinutes()*60_000)}},take:50,orderBy:{findingRunnerAt:"asc"},select:{id:true,createdAt:true}}),db.productRequest.findMany({where:{status:"CHECKING",updatedAt:{lte:new Date(now.getTime()-24*60*60_000)}},take:50,orderBy:{updatedAt:"asc"},select:{id:true,requestedName:true,updatedAt:true,user:{select:{email:true}}}})]);
 return <main className="min-h-screen bg-[#f7f5ee]"><div className="packam-container py-8"><h1 className="text-3xl font-black">Operational exceptions</h1><div className="mt-5 grid gap-4 lg:grid-cols-2"><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Incidents · {incidents.length}</h2>{incidents.map(i=><p key={i.id} className="mt-3 text-sm"><strong>{i.type}</strong> · {i.status} · {i.description} · <Link className="underline" href={`/admin/orders/${i.order.id}`}>Order</Link></p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Price approval waiting · {priceChanges.length}</h2>{priceChanges.map(s=><p key={s.id} className="mt-3 text-sm">{s.orderItem.productName} · {s.orderSource.vendor.name} · ₦{s.catalogueUnitPrice.toLocaleString()} → ₦{s.actualUnitPrice?.toLocaleString()} · <Link className="underline" href={`/admin/orders/${s.orderItem.order.id}`}>Order</Link></p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Payment reconciliation · {payments.length}</h2>{payments.map(p=><p key={p.id} className="mt-3 text-sm">{p.status} · {p.user.email} · ₦{p.amount.toLocaleString()} · <Link className="underline" href="/admin/payments">Payments</Link></p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Failed refunds · {refunds.length}</h2>{refunds.map(r=><p key={r.id} className="mt-3 text-sm">₦{r.amount.toLocaleString()} · {r.reason} · <Link className="underline" href={`/admin/orders/${r.order.id}`}>Order</Link></p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Runner overdue · {oldOrders.length}</h2>{oldOrders.map(o=><p key={o.id} className="mt-3 text-sm"><Link className="underline" href={`/admin/orders/${o.id}`}>{o.id}</Link> · {o.createdAt.toLocaleString()}</p>)}</section><section className="rounded-2xl bg-white p-5"><h2 className="font-black">Requests checking over 24 hours · {staleRequests.length}</h2>{staleRequests.map(r=><p key={r.id} className="mt-3 text-sm">{r.requestedName} · {r.user.email} · <Link className="underline" href="/admin/requests?status=CHECKING">Open requests</Link></p>)}</section></div></div></main>;
}
